[int_cam3946]
name = "int_cam3946"
size = [ 2704, 1520]
matrix = [ [ 1302.8435256219627, 0.0, 1347.523545573931], [ 0.0, 1303.958735939764, 754.8559170149753], [ 0.0, 0.0, 1.0]]
distortions = [ 0.013907374828198272, -0.01632490811659157, -0.0007584302310272389, 0.0012064012843266622]
rotation = [ 1.581421065525556, 0.60934573948407, -0.5034037362266516]
translation = [ -2.344573707715294, 1.1370223764824838, 4.605587656853296]
fisheye = false

[int_cam0677]
name = "int_cam0677"
size = [ 2704, 1520]
matrix = [ [ 1306.121472534038, 0.0, 1349.954891202943], [ 0.0, 1307.2769789116253, 759.9410977578369], [ 0.0, 0.0, 1.0]]
distortions = [ 0.010721751632722031, -0.008343564595798724, 0.00032819189154853436, 0.0009510638484834852]
rotation = [ 1.6028579617762064, 0.7296038434717778, -0.6496638047948]
translation = [ -10.381167483679748, 1.869612648931313, -1.7419420808624249]
fisheye = false

[int_cam8577]
name = "int_cam8577"
size = [ 2704, 1520]
matrix = [ [ 1304.050805663, 0.0, 1353.006712587745], [ 0.0, 1305.0168195016647, 764.4493088369065], [ 0.0, 0.0, 1.0]]
distortions = [ 0.008067680311366664, -0.005912477978235952, 0.0010181753212951928, 0.0010271143339052292]
rotation = [ 0.8752540091603901, 1.8938726932769863, -1.5491076005761812]
translation = [ -6.51558455319759, -0.6975863969036744, 11.976118826023884]
fisheye = false

[int_cam2189]
name = "int_cam2189"
size = [ 2704, 1520]
matrix = [ [ 1312.0146508461244, 0.0, 1354.8789080652627], [ 0.0, 1313.0201207544499, 770.9510508571035], [ 0.0, 0.0, 1.0]]
distortions = [ 0.008440374401743854, -0.002079303877514546, 0.0009753123402595214, 0.0019064347839258886]
rotation = [ 0.6848721604389991, 2.0669237277629287, -1.6474700094533063]
translation = [ -9.070034802611325, -3.1267121952468218, 20.18044129540531]
fisheye = false

[int_cam8672]
name = "int_cam8672"
size = [ 2704, 1520]
matrix = [ [ 1311.3315186789364, 0.0, 1342.2827546935803], [ 0.0, 1312.7938176052057, 750.0223032934302], [ 0.0, 0.0, 1.0]]
distortions = [ 0.01418364612935962, -0.011126336455189798, -0.002420926143562267, -0.0005805294645267402]
rotation = [ 0.5346268869064951, -2.114023946563243, 1.806309978987303]
translation = [ 9.271655198457214, -1.683197534627122, 20.681135875366643]
fisheye = false

[int_cam8635]
name = "int_cam8635"
size = [ 2704, 1520]
matrix = [ [ 1304.4224581188587, 0.0, 1345.8869123295756], [ 0.0, 1305.0954973652865, 757.4616448961665], [ 0.0, 0.0, 1.0]]
distortions = [ 0.01529113752849946, -0.010000927878567737, -0.0005773941628799425, -0.0007716702664565602]
rotation = [ 0.7951444354978375, -1.8944348716902242, 1.639861093212419]
translation = [ 6.697317377390438, 0.18746369185433778, 9.383624077834986]
fisheye = false

[int_cam3495]
name = "int_cam3495"
size = [ 2704, 1520]
matrix = [ [ 1426.820318531924, 0.0, 1338.6383139881389], [ 0.0, 1428.702126102691, 758.4336146629227], [ 0.0, 0.0, 1.0]]
distortions = [ 0.0006300287767134399, 0.0015062568428760206, -0.0012948487050958007, -0.0008631423590664885]
rotation = [ 1.5880100522261966, -0.7164204944089695, 0.6070661747194191]
translation = [ 7.422892201836226, 2.0831112792418356, -3.338334699965612]
fisheye = false

[int_cam5220]
name = "int_cam5220"
size = [ 2704, 1520]
matrix = [ [ 1303.494834170912, 0.0, 1329.4641049962468], [ 0.0, 1304.7466121422065, 754.1445136592546], [ 0.0, 0.0, 1.0]]
distortions = [ -0.001288804756800472, 0.0050244283195177, -0.0017536594329172909, -0.0029733002086976285]
rotation = [ 0.8589379310489197, -1.9044782325055214, 1.584290780742873]
translation = [ 2.59304251056029, 0.24777667766274244, 4.65723977925211]
fisheye = false

[int_cam8351]
name = "int_cam8351"
size = [ 2704, 1520]
matrix = [ [ 1314.2405652117036, 0.0, 1347.7083457049443], [ 0.0, 1315.746547081461, 752.5491640598576], [ 0.0, 0.0, 1.0]]
distortions = [ 0.004194491563660284, 0.0018369814338155877, -0.0020801507670406816, -0.0008754574490980829]
rotation = [ 1.7062834568950043, -0.5067609984666402, 0.41573694276168693]
translation = [ 0.15655707303741578, 1.0775506393764989, 3.4264741561898946]
fisheye = false

[metadata]
adjusted = false
error = 0.0
